require 'bundler/gem_tasks'
require 'rspec/core/rake_task'
require 'helix_runtime/build_task'

HelixRuntime::BuildTask.new

RSpec::Core::RakeTask.new(:spec)

task :spec => :build
task :default => :spec
